// Generated directly from TIDAS JSON Schema: tidas_locations_category.json
import { z } from 'zod';
import { jsonSchemaOneOf } from './../core/validation/json-schema';

export const LocationsCategorySchema = jsonSchemaOneOf(
  [
    z.literal('NULL') as z.ZodType,
    z.literal('GLO') as z.ZodType,
    z.literal('RoW') as z.ZodType,
    z.literal('RAF') as z.ZodType,
    z.literal('RAM') as z.ZodType,
    z.literal('RAS') as z.ZodType,
    z.literal('RER') as z.ZodType,
    z.literal('OCE') as z.ZodType,
    z.literal('MEA') as z.ZodType,
    z.literal('AFR') as z.ZodType,
    z.literal('RLA') as z.ZodType,
    z.literal('RNA') as z.ZodType,
    z.literal('CPA') as z.ZodType,
    z.literal('EAS') as z.ZodType,
    z.literal('PAS') as z.ZodType,
    z.literal('SAS') as z.ZodType,
    z.literal('EEU') as z.ZodType,
    z.literal('WEU') as z.ZodType,
    z.literal('RNE') as z.ZodType,
    z.literal('RME') as z.ZodType,
    z.literal('EU-15') as z.ZodType,
    z.literal('EU-NMC') as z.ZodType,
    z.literal('EU-25') as z.ZodType,
    z.literal('EC-CC') as z.ZodType,
    z.literal('EU-25&CC') as z.ZodType,
    z.literal('EU-AC') as z.ZodType,
    z.literal('EU-25&CC&AC') as z.ZodType,
    z.literal('EU-27') as z.ZodType,
    z.literal('PAO') as z.ZodType,
    z.literal('FSU') as z.ZodType,
    z.literal('UCTE') as z.ZodType,
    z.literal('CENTREL') as z.ZodType,
    z.literal('NORDEL') as z.ZodType,
    z.literal('EU+EFTA+UK') as z.ZodType,
    z.literal('AD') as z.ZodType,
    z.literal('AE') as z.ZodType,
    z.literal('AF') as z.ZodType,
    z.literal('AG') as z.ZodType,
    z.literal('AI') as z.ZodType,
    z.literal('AL') as z.ZodType,
    z.literal('AM') as z.ZodType,
    z.literal('AO') as z.ZodType,
    z.literal('AQ') as z.ZodType,
    z.literal('AR') as z.ZodType,
    z.literal('AS') as z.ZodType,
    z.literal('AT') as z.ZodType,
    z.literal('AU') as z.ZodType,
    z.literal('AW') as z.ZodType,
    z.literal('AX') as z.ZodType,
    z.literal('AZ') as z.ZodType,
    z.literal('BA') as z.ZodType,
    z.literal('BB') as z.ZodType,
    z.literal('BD') as z.ZodType,
    z.literal('BE') as z.ZodType,
    z.literal('BF') as z.ZodType,
    z.literal('BG') as z.ZodType,
    z.literal('BH') as z.ZodType,
    z.literal('BI') as z.ZodType,
    z.literal('BJ') as z.ZodType,
    z.literal('BL') as z.ZodType,
    z.literal('BM') as z.ZodType,
    z.literal('BN') as z.ZodType,
    z.literal('BO') as z.ZodType,
    z.literal('BQ') as z.ZodType,
    z.literal('BR') as z.ZodType,
    z.literal('BS') as z.ZodType,
    z.literal('BT') as z.ZodType,
    z.literal('BV') as z.ZodType,
    z.literal('BW') as z.ZodType,
    z.literal('BY') as z.ZodType,
    z.literal('BZ') as z.ZodType,
    z.literal('CA') as z.ZodType,
    z.literal('CC') as z.ZodType,
    z.literal('CD') as z.ZodType,
    z.literal('CF') as z.ZodType,
    z.literal('CG') as z.ZodType,
    z.literal('CH') as z.ZodType,
    z.literal('CI') as z.ZodType,
    z.literal('CK') as z.ZodType,
    z.literal('CL') as z.ZodType,
    z.literal('CM') as z.ZodType,
    z.literal('CO') as z.ZodType,
    z.literal('CR') as z.ZodType,
    z.literal('CU') as z.ZodType,
    z.literal('CV') as z.ZodType,
    z.literal('CW') as z.ZodType,
    z.literal('CX') as z.ZodType,
    z.literal('CY') as z.ZodType,
    z.literal('CZ') as z.ZodType,
    z.literal('DE') as z.ZodType,
    z.literal('DJ') as z.ZodType,
    z.literal('DK') as z.ZodType,
    z.literal('DM') as z.ZodType,
    z.literal('DO') as z.ZodType,
    z.literal('DZ') as z.ZodType,
    z.literal('EC') as z.ZodType,
    z.literal('EE') as z.ZodType,
    z.literal('EG') as z.ZodType,
    z.literal('EH') as z.ZodType,
    z.literal('ER') as z.ZodType,
    z.literal('ES') as z.ZodType,
    z.literal('ET') as z.ZodType,
    z.literal('FI') as z.ZodType,
    z.literal('FJ') as z.ZodType,
    z.literal('FK') as z.ZodType,
    z.literal('FM') as z.ZodType,
    z.literal('FO') as z.ZodType,
    z.literal('FR') as z.ZodType,
    z.literal('GA') as z.ZodType,
    z.literal('GB') as z.ZodType,
    z.literal('GD') as z.ZodType,
    z.literal('GE') as z.ZodType,
    z.literal('GF') as z.ZodType,
    z.literal('GG') as z.ZodType,
    z.literal('GH') as z.ZodType,
    z.literal('GI') as z.ZodType,
    z.literal('GL') as z.ZodType,
    z.literal('GM') as z.ZodType,
    z.literal('GN') as z.ZodType,
    z.literal('GP') as z.ZodType,
    z.literal('GQ') as z.ZodType,
    z.literal('GR') as z.ZodType,
    z.literal('GS') as z.ZodType,
    z.literal('GT') as z.ZodType,
    z.literal('GU') as z.ZodType,
    z.literal('GW') as z.ZodType,
    z.literal('GY') as z.ZodType,
    z.literal('HM') as z.ZodType,
    z.literal('HN') as z.ZodType,
    z.literal('HR') as z.ZodType,
    z.literal('HT') as z.ZodType,
    z.literal('HU') as z.ZodType,
    z.literal('ID') as z.ZodType,
    z.literal('IE') as z.ZodType,
    z.literal('IL') as z.ZodType,
    z.literal('IM') as z.ZodType,
    z.literal('IN') as z.ZodType,
    z.literal('IO') as z.ZodType,
    z.literal('IQ') as z.ZodType,
    z.literal('IR') as z.ZodType,
    z.literal('IS') as z.ZodType,
    z.literal('IT') as z.ZodType,
    z.literal('JE') as z.ZodType,
    z.literal('JM') as z.ZodType,
    z.literal('JO') as z.ZodType,
    z.literal('JP') as z.ZodType,
    z.literal('KE') as z.ZodType,
    z.literal('KG') as z.ZodType,
    z.literal('KH') as z.ZodType,
    z.literal('KI') as z.ZodType,
    z.literal('KM') as z.ZodType,
    z.literal('KN') as z.ZodType,
    z.literal('KP') as z.ZodType,
    z.literal('KR') as z.ZodType,
    z.literal('KW') as z.ZodType,
    z.literal('KY') as z.ZodType,
    z.literal('KZ') as z.ZodType,
    z.literal('LA') as z.ZodType,
    z.literal('LB') as z.ZodType,
    z.literal('LC') as z.ZodType,
    z.literal('LI') as z.ZodType,
    z.literal('LK') as z.ZodType,
    z.literal('LR') as z.ZodType,
    z.literal('LS') as z.ZodType,
    z.literal('LT') as z.ZodType,
    z.literal('LU') as z.ZodType,
    z.literal('LV') as z.ZodType,
    z.literal('LY') as z.ZodType,
    z.literal('MA') as z.ZodType,
    z.literal('MC') as z.ZodType,
    z.literal('MD') as z.ZodType,
    z.literal('ME') as z.ZodType,
    z.literal('MF') as z.ZodType,
    z.literal('MG') as z.ZodType,
    z.literal('MH') as z.ZodType,
    z.literal('MK') as z.ZodType,
    z.literal('ML') as z.ZodType,
    z.literal('MM') as z.ZodType,
    z.literal('MN') as z.ZodType,
    z.literal('MP') as z.ZodType,
    z.literal('MQ') as z.ZodType,
    z.literal('MR') as z.ZodType,
    z.literal('MS') as z.ZodType,
    z.literal('MT') as z.ZodType,
    z.literal('MU') as z.ZodType,
    z.literal('MV') as z.ZodType,
    z.literal('MW') as z.ZodType,
    z.literal('MX') as z.ZodType,
    z.literal('MY') as z.ZodType,
    z.literal('MZ') as z.ZodType,
    z.literal('NA') as z.ZodType,
    z.literal('NC') as z.ZodType,
    z.literal('NE') as z.ZodType,
    z.literal('NF') as z.ZodType,
    z.literal('NG') as z.ZodType,
    z.literal('NI') as z.ZodType,
    z.literal('NL') as z.ZodType,
    z.literal('NO') as z.ZodType,
    z.literal('NP') as z.ZodType,
    z.literal('NR') as z.ZodType,
    z.literal('NU') as z.ZodType,
    z.literal('NZ') as z.ZodType,
    z.literal('OM') as z.ZodType,
    z.literal('PA') as z.ZodType,
    z.literal('PE') as z.ZodType,
    z.literal('PF') as z.ZodType,
    z.literal('PG') as z.ZodType,
    z.literal('PH') as z.ZodType,
    z.literal('PK') as z.ZodType,
    z.literal('PL') as z.ZodType,
    z.literal('PM') as z.ZodType,
    z.literal('PN') as z.ZodType,
    z.literal('PR') as z.ZodType,
    z.literal('PS') as z.ZodType,
    z.literal('PT') as z.ZodType,
    z.literal('PW') as z.ZodType,
    z.literal('PY') as z.ZodType,
    z.literal('QA') as z.ZodType,
    z.literal('RE') as z.ZodType,
    z.literal('RO') as z.ZodType,
    z.literal('RS') as z.ZodType,
    z.literal('RU') as z.ZodType,
    z.literal('RW') as z.ZodType,
    z.literal('SA') as z.ZodType,
    z.literal('SB') as z.ZodType,
    z.literal('SC') as z.ZodType,
    z.literal('SD') as z.ZodType,
    z.literal('SE') as z.ZodType,
    z.literal('SG') as z.ZodType,
    z.literal('SH') as z.ZodType,
    z.literal('SI') as z.ZodType,
    z.literal('SJ') as z.ZodType,
    z.literal('SK') as z.ZodType,
    z.literal('SL') as z.ZodType,
    z.literal('SM') as z.ZodType,
    z.literal('SN') as z.ZodType,
    z.literal('SO') as z.ZodType,
    z.literal('SR') as z.ZodType,
    z.literal('SS') as z.ZodType,
    z.literal('ST') as z.ZodType,
    z.literal('SV') as z.ZodType,
    z.literal('SX') as z.ZodType,
    z.literal('SY') as z.ZodType,
    z.literal('SZ') as z.ZodType,
    z.literal('TC') as z.ZodType,
    z.literal('TD') as z.ZodType,
    z.literal('TF') as z.ZodType,
    z.literal('TG') as z.ZodType,
    z.literal('TH') as z.ZodType,
    z.literal('TJ') as z.ZodType,
    z.literal('TK') as z.ZodType,
    z.literal('TL') as z.ZodType,
    z.literal('TM') as z.ZodType,
    z.literal('TN') as z.ZodType,
    z.literal('TO') as z.ZodType,
    z.literal('TR') as z.ZodType,
    z.literal('TT') as z.ZodType,
    z.literal('TV') as z.ZodType,
    z.literal('TZ') as z.ZodType,
    z.literal('UA') as z.ZodType,
    z.literal('UG') as z.ZodType,
    z.literal('UM') as z.ZodType,
    z.literal('US') as z.ZodType,
    z.literal('UY') as z.ZodType,
    z.literal('UZ') as z.ZodType,
    z.literal('VA') as z.ZodType,
    z.literal('VC') as z.ZodType,
    z.literal('VE') as z.ZodType,
    z.literal('VG') as z.ZodType,
    z.literal('VI') as z.ZodType,
    z.literal('VN') as z.ZodType,
    z.literal('VU') as z.ZodType,
    z.literal('WF') as z.ZodType,
    z.literal('WS') as z.ZodType,
    z.literal('YE') as z.ZodType,
    z.literal('YT') as z.ZodType,
    z.literal('ZA') as z.ZodType,
    z.literal('ZM') as z.ZodType,
    z.literal('ZW') as z.ZodType,
    z.literal('CIS') as z.ZodType,
    z.literal('CN') as z.ZodType,
    z.literal('CN-BJ') as z.ZodType,
    z.literal('CN-TJ') as z.ZodType,
    z.literal('CN-HE') as z.ZodType,
    z.literal('CN-HE-SJW') as z.ZodType,
    z.literal('CN-HE-TGS') as z.ZodType,
    z.literal('CN-HE-SHP') as z.ZodType,
    z.literal('CN-HE-HDS') as z.ZodType,
    z.literal('CN-HE-XTS') as z.ZodType,
    z.literal('CN-HE-BDS') as z.ZodType,
    z.literal('CN-HE-ZJK') as z.ZodType,
    z.literal('CN-HE-CDS') as z.ZodType,
    z.literal('CN-HE-CGZ') as z.ZodType,
    z.literal('CN-HE-LFS') as z.ZodType,
    z.literal('CN-HE-HGS') as z.ZodType,
    z.literal('CN-SX') as z.ZodType,
    z.literal('CN-SX-TYN') as z.ZodType,
    z.literal('CN-SX-DTG') as z.ZodType,
    z.literal('CN-SX-YQS') as z.ZodType,
    z.literal('CN-SX-CZS') as z.ZodType,
    z.literal('CN-SX-JCG') as z.ZodType,
    z.literal('CN-SX-SZJ') as z.ZodType,
    z.literal('CN-SX-JZN') as z.ZodType,
    z.literal('CN-SX-YCE') as z.ZodType,
    z.literal('CN-SX-XZS') as z.ZodType,
    z.literal('CN-SX-LFN') as z.ZodType,
    z.literal('CN-SX-LLH') as z.ZodType,
    z.literal('CN-NM') as z.ZodType,
    z.literal('CN-NM-HET') as z.ZodType,
    z.literal('CN-NM-BTS') as z.ZodType,
    z.literal('CN-NM-WHM') as z.ZodType,
    z.literal('CN-NM-CFS') as z.ZodType,
    z.literal('CN-NM-TLO') as z.ZodType,
    z.literal('CN-NM-ODS') as z.ZodType,
    z.literal('CN-NM-HBR') as z.ZodType,
    z.literal('CN-NM-BYR') as z.ZodType,
    z.literal('CN-NM-ULS') as z.ZodType,
    z.literal('CN-NM-HIN') as z.ZodType,
    z.literal('CN-NM-XGO') as z.ZodType,
    z.literal('CN-NM-ALM') as z.ZodType,
    z.literal('CN-LN') as z.ZodType,
    z.literal('CN-LN-SHE') as z.ZodType,
    z.literal('CN-LN-DLC') as z.ZodType,
    z.literal('CN-LN-ASN') as z.ZodType,
    z.literal('CN-LN-FSN') as z.ZodType,
    z.literal('CN-LN-BXS') as z.ZodType,
    z.literal('CN-LN-DDG') as z.ZodType,
    z.literal('CN-LN-JNZ') as z.ZodType,
    z.literal('CN-LN-YIK') as z.ZodType,
    z.literal('CN-LN-FXS') as z.ZodType,
    z.literal('CN-LN-LYL') as z.ZodType,
    z.literal('CN-LN-PJS') as z.ZodType,
    z.literal('CN-LN-TLS') as z.ZodType,
    z.literal('CN-LN-CYS') as z.ZodType,
    z.literal('CN-LN-HLD') as z.ZodType,
    z.literal('CN-JL') as z.ZodType,
    z.literal('CN-JL-CGQ') as z.ZodType,
    z.literal('CN-JL-JLS') as z.ZodType,
    z.literal('CN-JL-SPS') as z.ZodType,
    z.literal('CN-JL-LYH') as z.ZodType,
    z.literal('CN-JL-THS') as z.ZodType,
    z.literal('CN-JL-BSN') as z.ZodType,
    z.literal('CN-JL-SYU') as z.ZodType,
    z.literal('CN-JL-BCS') as z.ZodType,
    z.literal('CN-JL-YBZ') as z.ZodType,
    z.literal('CN-HL') as z.ZodType,
    z.literal('CN-HL-HRB') as z.ZodType,
    z.literal('CN-HL-NDG') as z.ZodType,
    z.literal('CN-HL-JXI') as z.ZodType,
    z.literal('CN-HL-HEG') as z.ZodType,
    z.literal('CN-HL-SYS') as z.ZodType,
    z.literal('CN-HL-DQG') as z.ZodType,
    z.literal('CN-HL-YCH') as z.ZodType,
    z.literal('CN-HL-JMU') as z.ZodType,
    z.literal('CN-HL-QTH') as z.ZodType,
    z.literal('CN-HL-MDG') as z.ZodType,
    z.literal('CN-HL-HEK') as z.ZodType,
    z.literal('CN-HL-SUH') as z.ZodType,
    z.literal('CN-HL-DHL') as z.ZodType,
    z.literal('CN-SH') as z.ZodType,
    z.literal('CN-JS') as z.ZodType,
    z.literal('CN-JS-NKG') as z.ZodType,
    z.literal('CN-JS-WUX') as z.ZodType,
    z.literal('CN-JS-XUZ') as z.ZodType,
    z.literal('CN-JS-CZX') as z.ZodType,
    z.literal('CN-JS-SZH') as z.ZodType,
    z.literal('CN-JS-NTG') as z.ZodType,
    z.literal('CN-JS-LYG') as z.ZodType,
    z.literal('CN-JS-HAS') as z.ZodType,
    z.literal('CN-JS-YCK') as z.ZodType,
    z.literal('CN-JS-YZH') as z.ZodType,
    z.literal('CN-JS-ZHE') as z.ZodType,
    z.literal('CN-JS-TZS') as z.ZodType,
    z.literal('CN-JS-SUQ') as z.ZodType,
    z.literal('CN-ZJ') as z.ZodType,
    z.literal('CN-ZJ-HGH') as z.ZodType,
    z.literal('CN-ZJ-NGB') as z.ZodType,
    z.literal('CN-ZJ-WNZ') as z.ZodType,
    z.literal('CN-ZJ-JIX') as z.ZodType,
    z.literal('CN-ZJ-HZH') as z.ZodType,
    z.literal('CN-ZJ-SXG') as z.ZodType,
    z.literal('CN-ZJ-JHA') as z.ZodType,
    z.literal('CN-ZJ-QUZ') as z.ZodType,
    z.literal('CN-ZJ-ZOS') as z.ZodType,
    z.literal('CN-ZJ-TZZ') as z.ZodType,
    z.literal('CN-ZJ-LSS') as z.ZodType,
    z.literal('CN-AH') as z.ZodType,
    z.literal('CN-AH-HFE') as z.ZodType,
    z.literal('CN-AH-WHI') as z.ZodType,
    z.literal('CN-AH-BBU') as z.ZodType,
    z.literal('CN-AH-HNS') as z.ZodType,
    z.literal('CN-AH-MAA') as z.ZodType,
    z.literal('CN-AH-HBE') as z.ZodType,
    z.literal('CN-AH-TOL') as z.ZodType,
    z.literal('CN-AH-AQG') as z.ZodType,
    z.literal('CN-AH-HSN') as z.ZodType,
    z.literal('CN-AH-CUZ') as z.ZodType,
    z.literal('CN-AH-FYS') as z.ZodType,
    z.literal('CN-AH-SUZ') as z.ZodType,
    z.literal('CN-AH-CAH') as z.ZodType,
    z.literal('CN-AH-LAW') as z.ZodType,
    z.literal('CN-AH-BOZ') as z.ZodType,
    z.literal('CN-AH-CIZ') as z.ZodType,
    z.literal('CN-AH-XCI') as z.ZodType,
    z.literal('CN-FJ') as z.ZodType,
    z.literal('CN-FJ-FOC') as z.ZodType,
    z.literal('CN-FJ-XMN') as z.ZodType,
    z.literal('CN-FJ-PUT') as z.ZodType,
    z.literal('CN-FJ-SMS') as z.ZodType,
    z.literal('CN-FJ-QZJ') as z.ZodType,
    z.literal('CN-FJ-ZZU') as z.ZodType,
    z.literal('CN-FJ-NPS') as z.ZodType,
    z.literal('CN-FJ-LYF') as z.ZodType,
    z.literal('CN-FJ-NDS') as z.ZodType,
    z.literal('CN-JX') as z.ZodType,
    z.literal('CN-JX-KHN') as z.ZodType,
    z.literal('CN-JX-JDZ') as z.ZodType,
    z.literal('CN-JX-PXS') as z.ZodType,
    z.literal('CN-JX-JIU') as z.ZodType,
    z.literal('CN-JX-XYU') as z.ZodType,
    z.literal('CN-JX-YTS') as z.ZodType,
    z.literal('CN-JX-GZH') as z.ZodType,
    z.literal('CN-JX-JAS') as z.ZodType,
    z.literal('CN-JX-YCN') as z.ZodType,
    z.literal('CN-JX-FUZ') as z.ZodType,
    z.literal('CN-JX-SRS') as z.ZodType,
    z.literal('CN-SD') as z.ZodType,
    z.literal('CN-SD-TNA') as z.ZodType,
    z.literal('CN-SD-TAO') as z.ZodType,
    z.literal('CN-SD-ZBO') as z.ZodType,
    z.literal('CN-SD-ZZG') as z.ZodType,
    z.literal('CN-SD-DYG') as z.ZodType,
    z.literal('CN-SD-YNT') as z.ZodType,
    z.literal('CN-SD-WEF') as z.ZodType,
    z.literal('CN-SD-JNG') as z.ZodType,
    z.literal('CN-SD-TAI') as z.ZodType,
    z.literal('CN-SD-WEH') as z.ZodType,
    z.literal('CN-SD-RZH') as z.ZodType,
    z.literal('CN-SD-LWS') as z.ZodType,
    z.literal('CN-SD-LYI') as z.ZodType,
    z.literal('CN-SD-DZS') as z.ZodType,
    z.literal('CN-SD-LCH') as z.ZodType,
    z.literal('CN-SD-BZH') as z.ZodType,
    z.literal('CN-SD-HZS') as z.ZodType,
    z.literal('CN-HA') as z.ZodType,
    z.literal('CN-HA-CGO') as z.ZodType,
    z.literal('CN-HA-KFS') as z.ZodType,
    z.literal('CN-HA-LYA') as z.ZodType,
    z.literal('CN-HA-PDS') as z.ZodType,
    z.literal('CN-HA-AYS') as z.ZodType,
    z.literal('CN-HA-HBS') as z.ZodType,
    z.literal('CN-HA-XXS') as z.ZodType,
    z.literal('CN-HA-JZY') as z.ZodType,
    z.literal('CN-HA-PYS') as z.ZodType,
    z.literal('CN-HA-XCS') as z.ZodType,
    z.literal('CN-HA-LHS') as z.ZodType,
    z.literal('CN-HA-SMX') as z.ZodType,
    z.literal('CN-HA-NYS') as z.ZodType,
    z.literal('CN-HA-SQS') as z.ZodType,
    z.literal('CN-HA-XYG') as z.ZodType,
    z.literal('CN-HA-ZKS') as z.ZodType,
    z.literal('CN-HA-ZMD') as z.ZodType,
    z.literal('CN-HB') as z.ZodType,
    z.literal('CN-HB-WUH') as z.ZodType,
    z.literal('CN-HB-HSI') as z.ZodType,
    z.literal('CN-HB-SYE') as z.ZodType,
    z.literal('CN-HB-YCO') as z.ZodType,
    z.literal('CN-HB-XFN') as z.ZodType,
    z.literal('CN-HB-EZS') as z.ZodType,
    z.literal('CN-HB-JMS') as z.ZodType,
    z.literal('CN-HB-XGE') as z.ZodType,
    z.literal('CN-HB-JGZ') as z.ZodType,
    z.literal('CN-HB-HGE') as z.ZodType,
    z.literal('CN-HB-XNS') as z.ZodType,
    z.literal('CN-HB-SZR') as z.ZodType,
    z.literal('CN-HB-ESH') as z.ZodType,
    z.literal('CN-HN') as z.ZodType,
    z.literal('CN-HN-CSX') as z.ZodType,
    z.literal('CN-HN-ZZS') as z.ZodType,
    z.literal('CN-HN-XGT') as z.ZodType,
    z.literal('CN-HN-HNY') as z.ZodType,
    z.literal('CN-HN-SYR') as z.ZodType,
    z.literal('CN-HN-YYG') as z.ZodType,
    z.literal('CN-HN-CDE') as z.ZodType,
    z.literal('CN-HN-ZJJ') as z.ZodType,
    z.literal('CN-HN-YYS') as z.ZodType,
    z.literal('CN-HN-CNZ') as z.ZodType,
    z.literal('CN-HN-YZS') as z.ZodType,
    z.literal('CN-HN-HHS') as z.ZodType,
    z.literal('CN-HN-LDI') as z.ZodType,
    z.literal('CN-HN-XXZ') as z.ZodType,
    z.literal('CN-GD') as z.ZodType,
    z.literal('CN-GD-CAN') as z.ZodType,
    z.literal('CN-GD-HSC') as z.ZodType,
    z.literal('CN-GD-SZX') as z.ZodType,
    z.literal('CN-GD-ZUH') as z.ZodType,
    z.literal('CN-GD-SWA') as z.ZodType,
    z.literal('CN-GD-FOS') as z.ZodType,
    z.literal('CN-GD-JMN') as z.ZodType,
    z.literal('CN-GD-ZHA') as z.ZodType,
    z.literal('CN-GD-MMI') as z.ZodType,
    z.literal('CN-GD-ZQG') as z.ZodType,
    z.literal('CN-GD-HUI') as z.ZodType,
    z.literal('CN-GD-MXZ') as z.ZodType,
    z.literal('CN-GD-SWE') as z.ZodType,
    z.literal('CN-GD-HEY') as z.ZodType,
    z.literal('CN-GD-YJI') as z.ZodType,
    z.literal('CN-GD-QYN') as z.ZodType,
    z.literal('CN-GD-DGG') as z.ZodType,
    z.literal('CN-GD-ZSN') as z.ZodType,
    z.literal('CN-GD-CZY') as z.ZodType,
    z.literal('CN-GD-JIY') as z.ZodType,
    z.literal('CN-GD-YFS') as z.ZodType,
    z.literal('CN-GX') as z.ZodType,
    z.literal('CN-GX-NNG') as z.ZodType,
    z.literal('CN-GX-LZH') as z.ZodType,
    z.literal('CN-GX-KWL') as z.ZodType,
    z.literal('CN-GX-WUZ') as z.ZodType,
    z.literal('CN-GX-BHY') as z.ZodType,
    z.literal('CN-GX-FAN') as z.ZodType,
    z.literal('CN-GX-QZH') as z.ZodType,
    z.literal('CN-GX-GUG') as z.ZodType,
    z.literal('CN-GX-YUL') as z.ZodType,
    z.literal('CN-GX-BSS') as z.ZodType,
    z.literal('CN-GX-HZO') as z.ZodType,
    z.literal('CN-GX-HCS') as z.ZodType,
    z.literal('CN-GX-LIB') as z.ZodType,
    z.literal('CN-GX-COZ') as z.ZodType,
    z.literal('CN-HI') as z.ZodType,
    z.literal('CN-HI-HAK') as z.ZodType,
    z.literal('CN-HI-SYX') as z.ZodType,
    z.literal('CN-CQ') as z.ZodType,
    z.literal('CN-SC') as z.ZodType,
    z.literal('CN-SC-CTU') as z.ZodType,
    z.literal('CN-SC-ZGS') as z.ZodType,
    z.literal('CN-SC-PZH') as z.ZodType,
    z.literal('CN-SC-LUZ') as z.ZodType,
    z.literal('CN-SC-DEY') as z.ZodType,
    z.literal('CN-SC-MYG') as z.ZodType,
    z.literal('CN-SC-GYC') as z.ZodType,
    z.literal('CN-SC-SNS') as z.ZodType,
    z.literal('CN-SC-NJS') as z.ZodType,
    z.literal('CN-SC-LES') as z.ZodType,
    z.literal('CN-SC-NCO') as z.ZodType,
    z.literal('CN-SC-MSS') as z.ZodType,
    z.literal('CN-SC-YBS') as z.ZodType,
    z.literal('CN-SC-GAC') as z.ZodType,
    z.literal('CN-SC-DAZ') as z.ZodType,
    z.literal('CN-SC-YAS') as z.ZodType,
    z.literal('CN-SC-BZS') as z.ZodType,
    z.literal('CN-SC-ZYS') as z.ZodType,
    z.literal('CN-SC-ABA') as z.ZodType,
    z.literal('CN-SC-GAZ') as z.ZodType,
    z.literal('CN-SC-LSY') as z.ZodType,
    z.literal('CN-GZ') as z.ZodType,
    z.literal('CN-GZ-KWE') as z.ZodType,
    z.literal('CN-GZ-LPS') as z.ZodType,
    z.literal('CN-GZ-ZNY') as z.ZodType,
    z.literal('CN-GZ-ASS') as z.ZodType,
    z.literal('CN-GZ-TRD') as z.ZodType,
    z.literal('CN-GZ-QXZ') as z.ZodType,
    z.literal('CN-GZ-BJD') as z.ZodType,
    z.literal('CN-GZ-QND') as z.ZodType,
    z.literal('CN-GZ-QNZ') as z.ZodType,
    z.literal('CN-YN') as z.ZodType,
    z.literal('CN-YN-KMG') as z.ZodType,
    z.literal('CN-YN-QJS') as z.ZodType,
    z.literal('CN-YN-YXS') as z.ZodType,
    z.literal('CN-YN-BOS') as z.ZodType,
    z.literal('CN-YN-ZTS') as z.ZodType,
    z.literal('CN-YN-LJH') as z.ZodType,
    z.literal('CN-YN-PRS') as z.ZodType,
    z.literal('CN-YN-LIH') as z.ZodType,
    z.literal('CN-YN-CXD') as z.ZodType,
    z.literal('CN-YN-HHZ') as z.ZodType,
    z.literal('CN-YN-WSZ') as z.ZodType,
    z.literal('CN-YN-XSB') as z.ZodType,
    z.literal('CN-YN-DLZ') as z.ZodType,
    z.literal('CN-YN-DHG') as z.ZodType,
    z.literal('CN-YN-NUJ') as z.ZodType,
    z.literal('CN-YN-DEZ') as z.ZodType,
    z.literal('CN-XZ') as z.ZodType,
    z.literal('CN-XZ-LXA') as z.ZodType,
    z.literal('CN-XZ-QAD') as z.ZodType,
    z.literal('CN-XZ-SND') as z.ZodType,
    z.literal('CN-XZ-XID') as z.ZodType,
    z.literal('CN-XZ-NAD') as z.ZodType,
    z.literal('CN-XZ-NGD') as z.ZodType,
    z.literal('CN-XZ-NYD') as z.ZodType,
    z.literal('CN-SN') as z.ZodType,
    z.literal('CN-SN-SIA') as z.ZodType,
    z.literal('CN-SN-TCN') as z.ZodType,
    z.literal('CN-SN-BJI') as z.ZodType,
    z.literal('CN-SN-XYS') as z.ZodType,
    z.literal('CN-SN-WNA') as z.ZodType,
    z.literal('CN-SN-YNA') as z.ZodType,
    z.literal('CN-SN-HZJ') as z.ZodType,
    z.literal('CN-SN-YLN') as z.ZodType,
    z.literal('CN-SN-ANK') as z.ZodType,
    z.literal('CN-SN-SLH') as z.ZodType,
    z.literal('CN-GS') as z.ZodType,
    z.literal('CN-GS-LHW') as z.ZodType,
    z.literal('CN-GS-JYG') as z.ZodType,
    z.literal('CN-GS-JCS') as z.ZodType,
    z.literal('CN-GS-BYS') as z.ZodType,
    z.literal('CN-GS-TSU') as z.ZodType,
    z.literal('CN-GS-WWS') as z.ZodType,
    z.literal('CN-GS-ZYE') as z.ZodType,
    z.literal('CN-GS-PLS') as z.ZodType,
    z.literal('CN-GS-JQG') as z.ZodType,
    z.literal('CN-GS-QYI') as z.ZodType,
    z.literal('CN-GS-DNX') as z.ZodType,
    z.literal('CN-GS-LGN') as z.ZodType,
    z.literal('CN-GS-LXH') as z.ZodType,
    z.literal('CN-GS-GNZ') as z.ZodType,
    z.literal('CN-QH') as z.ZodType,
    z.literal('CN-QH-XNN') as z.ZodType,
    z.literal('CN-QH-HDD') as z.ZodType,
    z.literal('CN-QH-HBZ') as z.ZodType,
    z.literal('CN-QH-HN7') as z.ZodType,
    z.literal('CN-QH-HNN') as z.ZodType,
    z.literal('CN-QH-GOL') as z.ZodType,
    z.literal('CN-QH-YSZ') as z.ZodType,
    z.literal('CN-QH-HXZ') as z.ZodType,
    z.literal('CN-NX') as z.ZodType,
    z.literal('CN-NX-INC') as z.ZodType,
    z.literal('CN-NX-SZS') as z.ZodType,
    z.literal('CN-NX-WZS') as z.ZodType,
    z.literal('CN-NX-GYN') as z.ZodType,
    z.literal('CN-NX-ZWS') as z.ZodType,
    z.literal('CN-XJ') as z.ZodType,
    z.literal('CN-XJ-URC') as z.ZodType,
    z.literal('CN-XJ-KAR') as z.ZodType,
    z.literal('CN-XJ-TUD') as z.ZodType,
    z.literal('CN-XJ-HMD') as z.ZodType,
    z.literal('CN-XJ-CJZ') as z.ZodType,
    z.literal('CN-XJ-BOR') as z.ZodType,
    z.literal('CN-XJ-BAG') as z.ZodType,
    z.literal('CN-XJ-AKD') as z.ZodType,
    z.literal('CN-XJ-KIZ') as z.ZodType,
    z.literal('CN-XJ-KSI') as z.ZodType,
    z.literal('CN-XJ-HOD') as z.ZodType,
    z.literal('CN-XJ-ILD') as z.ZodType,
    z.literal('CN-XJ-TCD') as z.ZodType,
    z.literal('CN-XJ-ALD') as z.ZodType,
    z.literal('TW') as z.ZodType,
    z.literal('HK') as z.ZodType,
    z.literal('MO') as z.ZodType,
  ] as z.ZodType[],
  {
    values: [
      'NULL',
      'GLO',
      'RoW',
      'RAF',
      'RAM',
      'RAS',
      'RER',
      'OCE',
      'MEA',
      'AFR',
      'RLA',
      'RNA',
      'CPA',
      'EAS',
      'PAS',
      'SAS',
      'EEU',
      'WEU',
      'RNE',
      'RME',
      'EU-15',
      'EU-NMC',
      'EU-25',
      'EC-CC',
      'EU-25&CC',
      'EU-AC',
      'EU-25&CC&AC',
      'EU-27',
      'PAO',
      'FSU',
      'UCTE',
      'CENTREL',
      'NORDEL',
      'EU+EFTA+UK',
      'AD',
      'AE',
      'AF',
      'AG',
      'AI',
      'AL',
      'AM',
      'AO',
      'AQ',
      'AR',
      'AS',
      'AT',
      'AU',
      'AW',
      'AX',
      'AZ',
      'BA',
      'BB',
      'BD',
      'BE',
      'BF',
      'BG',
      'BH',
      'BI',
      'BJ',
      'BL',
      'BM',
      'BN',
      'BO',
      'BQ',
      'BR',
      'BS',
      'BT',
      'BV',
      'BW',
      'BY',
      'BZ',
      'CA',
      'CC',
      'CD',
      'CF',
      'CG',
      'CH',
      'CI',
      'CK',
      'CL',
      'CM',
      'CO',
      'CR',
      'CU',
      'CV',
      'CW',
      'CX',
      'CY',
      'CZ',
      'DE',
      'DJ',
      'DK',
      'DM',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'EH',
      'ER',
      'ES',
      'ET',
      'FI',
      'FJ',
      'FK',
      'FM',
      'FO',
      'FR',
      'GA',
      'GB',
      'GD',
      'GE',
      'GF',
      'GG',
      'GH',
      'GI',
      'GL',
      'GM',
      'GN',
      'GP',
      'GQ',
      'GR',
      'GS',
      'GT',
      'GU',
      'GW',
      'GY',
      'HM',
      'HN',
      'HR',
      'HT',
      'HU',
      'ID',
      'IE',
      'IL',
      'IM',
      'IN',
      'IO',
      'IQ',
      'IR',
      'IS',
      'IT',
      'JE',
      'JM',
      'JO',
      'JP',
      'KE',
      'KG',
      'KH',
      'KI',
      'KM',
      'KN',
      'KP',
      'KR',
      'KW',
      'KY',
      'KZ',
      'LA',
      'LB',
      'LC',
      'LI',
      'LK',
      'LR',
      'LS',
      'LT',
      'LU',
      'LV',
      'LY',
      'MA',
      'MC',
      'MD',
      'ME',
      'MF',
      'MG',
      'MH',
      'MK',
      'ML',
      'MM',
      'MN',
      'MP',
      'MQ',
      'MR',
      'MS',
      'MT',
      'MU',
      'MV',
      'MW',
      'MX',
      'MY',
      'MZ',
      'NA',
      'NC',
      'NE',
      'NF',
      'NG',
      'NI',
      'NL',
      'NO',
      'NP',
      'NR',
      'NU',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PF',
      'PG',
      'PH',
      'PK',
      'PL',
      'PM',
      'PN',
      'PR',
      'PS',
      'PT',
      'PW',
      'PY',
      'QA',
      'RE',
      'RO',
      'RS',
      'RU',
      'RW',
      'SA',
      'SB',
      'SC',
      'SD',
      'SE',
      'SG',
      'SH',
      'SI',
      'SJ',
      'SK',
      'SL',
      'SM',
      'SN',
      'SO',
      'SR',
      'SS',
      'ST',
      'SV',
      'SX',
      'SY',
      'SZ',
      'TC',
      'TD',
      'TF',
      'TG',
      'TH',
      'TJ',
      'TK',
      'TL',
      'TM',
      'TN',
      'TO',
      'TR',
      'TT',
      'TV',
      'TZ',
      'UA',
      'UG',
      'UM',
      'US',
      'UY',
      'UZ',
      'VA',
      'VC',
      'VE',
      'VG',
      'VI',
      'VN',
      'VU',
      'WF',
      'WS',
      'YE',
      'YT',
      'ZA',
      'ZM',
      'ZW',
      'CIS',
      'CN',
      'CN-BJ',
      'CN-TJ',
      'CN-HE',
      'CN-HE-SJW',
      'CN-HE-TGS',
      'CN-HE-SHP',
      'CN-HE-HDS',
      'CN-HE-XTS',
      'CN-HE-BDS',
      'CN-HE-ZJK',
      'CN-HE-CDS',
      'CN-HE-CGZ',
      'CN-HE-LFS',
      'CN-HE-HGS',
      'CN-SX',
      'CN-SX-TYN',
      'CN-SX-DTG',
      'CN-SX-YQS',
      'CN-SX-CZS',
      'CN-SX-JCG',
      'CN-SX-SZJ',
      'CN-SX-JZN',
      'CN-SX-YCE',
      'CN-SX-XZS',
      'CN-SX-LFN',
      'CN-SX-LLH',
      'CN-NM',
      'CN-NM-HET',
      'CN-NM-BTS',
      'CN-NM-WHM',
      'CN-NM-CFS',
      'CN-NM-TLO',
      'CN-NM-ODS',
      'CN-NM-HBR',
      'CN-NM-BYR',
      'CN-NM-ULS',
      'CN-NM-HIN',
      'CN-NM-XGO',
      'CN-NM-ALM',
      'CN-LN',
      'CN-LN-SHE',
      'CN-LN-DLC',
      'CN-LN-ASN',
      'CN-LN-FSN',
      'CN-LN-BXS',
      'CN-LN-DDG',
      'CN-LN-JNZ',
      'CN-LN-YIK',
      'CN-LN-FXS',
      'CN-LN-LYL',
      'CN-LN-PJS',
      'CN-LN-TLS',
      'CN-LN-CYS',
      'CN-LN-HLD',
      'CN-JL',
      'CN-JL-CGQ',
      'CN-JL-JLS',
      'CN-JL-SPS',
      'CN-JL-LYH',
      'CN-JL-THS',
      'CN-JL-BSN',
      'CN-JL-SYU',
      'CN-JL-BCS',
      'CN-JL-YBZ',
      'CN-HL',
      'CN-HL-HRB',
      'CN-HL-NDG',
      'CN-HL-JXI',
      'CN-HL-HEG',
      'CN-HL-SYS',
      'CN-HL-DQG',
      'CN-HL-YCH',
      'CN-HL-JMU',
      'CN-HL-QTH',
      'CN-HL-MDG',
      'CN-HL-HEK',
      'CN-HL-SUH',
      'CN-HL-DHL',
      'CN-SH',
      'CN-JS',
      'CN-JS-NKG',
      'CN-JS-WUX',
      'CN-JS-XUZ',
      'CN-JS-CZX',
      'CN-JS-SZH',
      'CN-JS-NTG',
      'CN-JS-LYG',
      'CN-JS-HAS',
      'CN-JS-YCK',
      'CN-JS-YZH',
      'CN-JS-ZHE',
      'CN-JS-TZS',
      'CN-JS-SUQ',
      'CN-ZJ',
      'CN-ZJ-HGH',
      'CN-ZJ-NGB',
      'CN-ZJ-WNZ',
      'CN-ZJ-JIX',
      'CN-ZJ-HZH',
      'CN-ZJ-SXG',
      'CN-ZJ-JHA',
      'CN-ZJ-QUZ',
      'CN-ZJ-ZOS',
      'CN-ZJ-TZZ',
      'CN-ZJ-LSS',
      'CN-AH',
      'CN-AH-HFE',
      'CN-AH-WHI',
      'CN-AH-BBU',
      'CN-AH-HNS',
      'CN-AH-MAA',
      'CN-AH-HBE',
      'CN-AH-TOL',
      'CN-AH-AQG',
      'CN-AH-HSN',
      'CN-AH-CUZ',
      'CN-AH-FYS',
      'CN-AH-SUZ',
      'CN-AH-CAH',
      'CN-AH-LAW',
      'CN-AH-BOZ',
      'CN-AH-CIZ',
      'CN-AH-XCI',
      'CN-FJ',
      'CN-FJ-FOC',
      'CN-FJ-XMN',
      'CN-FJ-PUT',
      'CN-FJ-SMS',
      'CN-FJ-QZJ',
      'CN-FJ-ZZU',
      'CN-FJ-NPS',
      'CN-FJ-LYF',
      'CN-FJ-NDS',
      'CN-JX',
      'CN-JX-KHN',
      'CN-JX-JDZ',
      'CN-JX-PXS',
      'CN-JX-JIU',
      'CN-JX-XYU',
      'CN-JX-YTS',
      'CN-JX-GZH',
      'CN-JX-JAS',
      'CN-JX-YCN',
      'CN-JX-FUZ',
      'CN-JX-SRS',
      'CN-SD',
      'CN-SD-TNA',
      'CN-SD-TAO',
      'CN-SD-ZBO',
      'CN-SD-ZZG',
      'CN-SD-DYG',
      'CN-SD-YNT',
      'CN-SD-WEF',
      'CN-SD-JNG',
      'CN-SD-TAI',
      'CN-SD-WEH',
      'CN-SD-RZH',
      'CN-SD-LWS',
      'CN-SD-LYI',
      'CN-SD-DZS',
      'CN-SD-LCH',
      'CN-SD-BZH',
      'CN-SD-HZS',
      'CN-HA',
      'CN-HA-CGO',
      'CN-HA-KFS',
      'CN-HA-LYA',
      'CN-HA-PDS',
      'CN-HA-AYS',
      'CN-HA-HBS',
      'CN-HA-XXS',
      'CN-HA-JZY',
      'CN-HA-PYS',
      'CN-HA-XCS',
      'CN-HA-LHS',
      'CN-HA-SMX',
      'CN-HA-NYS',
      'CN-HA-SQS',
      'CN-HA-XYG',
      'CN-HA-ZKS',
      'CN-HA-ZMD',
      'CN-HB',
      'CN-HB-WUH',
      'CN-HB-HSI',
      'CN-HB-SYE',
      'CN-HB-YCO',
      'CN-HB-XFN',
      'CN-HB-EZS',
      'CN-HB-JMS',
      'CN-HB-XGE',
      'CN-HB-JGZ',
      'CN-HB-HGE',
      'CN-HB-XNS',
      'CN-HB-SZR',
      'CN-HB-ESH',
      'CN-HN',
      'CN-HN-CSX',
      'CN-HN-ZZS',
      'CN-HN-XGT',
      'CN-HN-HNY',
      'CN-HN-SYR',
      'CN-HN-YYG',
      'CN-HN-CDE',
      'CN-HN-ZJJ',
      'CN-HN-YYS',
      'CN-HN-CNZ',
      'CN-HN-YZS',
      'CN-HN-HHS',
      'CN-HN-LDI',
      'CN-HN-XXZ',
      'CN-GD',
      'CN-GD-CAN',
      'CN-GD-HSC',
      'CN-GD-SZX',
      'CN-GD-ZUH',
      'CN-GD-SWA',
      'CN-GD-FOS',
      'CN-GD-JMN',
      'CN-GD-ZHA',
      'CN-GD-MMI',
      'CN-GD-ZQG',
      'CN-GD-HUI',
      'CN-GD-MXZ',
      'CN-GD-SWE',
      'CN-GD-HEY',
      'CN-GD-YJI',
      'CN-GD-QYN',
      'CN-GD-DGG',
      'CN-GD-ZSN',
      'CN-GD-CZY',
      'CN-GD-JIY',
      'CN-GD-YFS',
      'CN-GX',
      'CN-GX-NNG',
      'CN-GX-LZH',
      'CN-GX-KWL',
      'CN-GX-WUZ',
      'CN-GX-BHY',
      'CN-GX-FAN',
      'CN-GX-QZH',
      'CN-GX-GUG',
      'CN-GX-YUL',
      'CN-GX-BSS',
      'CN-GX-HZO',
      'CN-GX-HCS',
      'CN-GX-LIB',
      'CN-GX-COZ',
      'CN-HI',
      'CN-HI-HAK',
      'CN-HI-SYX',
      'CN-CQ',
      'CN-SC',
      'CN-SC-CTU',
      'CN-SC-ZGS',
      'CN-SC-PZH',
      'CN-SC-LUZ',
      'CN-SC-DEY',
      'CN-SC-MYG',
      'CN-SC-GYC',
      'CN-SC-SNS',
      'CN-SC-NJS',
      'CN-SC-LES',
      'CN-SC-NCO',
      'CN-SC-MSS',
      'CN-SC-YBS',
      'CN-SC-GAC',
      'CN-SC-DAZ',
      'CN-SC-YAS',
      'CN-SC-BZS',
      'CN-SC-ZYS',
      'CN-SC-ABA',
      'CN-SC-GAZ',
      'CN-SC-LSY',
      'CN-GZ',
      'CN-GZ-KWE',
      'CN-GZ-LPS',
      'CN-GZ-ZNY',
      'CN-GZ-ASS',
      'CN-GZ-TRD',
      'CN-GZ-QXZ',
      'CN-GZ-BJD',
      'CN-GZ-QND',
      'CN-GZ-QNZ',
      'CN-YN',
      'CN-YN-KMG',
      'CN-YN-QJS',
      'CN-YN-YXS',
      'CN-YN-BOS',
      'CN-YN-ZTS',
      'CN-YN-LJH',
      'CN-YN-PRS',
      'CN-YN-LIH',
      'CN-YN-CXD',
      'CN-YN-HHZ',
      'CN-YN-WSZ',
      'CN-YN-XSB',
      'CN-YN-DLZ',
      'CN-YN-DHG',
      'CN-YN-NUJ',
      'CN-YN-DEZ',
      'CN-XZ',
      'CN-XZ-LXA',
      'CN-XZ-QAD',
      'CN-XZ-SND',
      'CN-XZ-XID',
      'CN-XZ-NAD',
      'CN-XZ-NGD',
      'CN-XZ-NYD',
      'CN-SN',
      'CN-SN-SIA',
      'CN-SN-TCN',
      'CN-SN-BJI',
      'CN-SN-XYS',
      'CN-SN-WNA',
      'CN-SN-YNA',
      'CN-SN-HZJ',
      'CN-SN-YLN',
      'CN-SN-ANK',
      'CN-SN-SLH',
      'CN-GS',
      'CN-GS-LHW',
      'CN-GS-JYG',
      'CN-GS-JCS',
      'CN-GS-BYS',
      'CN-GS-TSU',
      'CN-GS-WWS',
      'CN-GS-ZYE',
      'CN-GS-PLS',
      'CN-GS-JQG',
      'CN-GS-QYI',
      'CN-GS-DNX',
      'CN-GS-LGN',
      'CN-GS-LXH',
      'CN-GS-GNZ',
      'CN-QH',
      'CN-QH-XNN',
      'CN-QH-HDD',
      'CN-QH-HBZ',
      'CN-QH-HN7',
      'CN-QH-HNN',
      'CN-QH-GOL',
      'CN-QH-YSZ',
      'CN-QH-HXZ',
      'CN-NX',
      'CN-NX-INC',
      'CN-NX-SZS',
      'CN-NX-WZS',
      'CN-NX-GYN',
      'CN-NX-ZWS',
      'CN-XJ',
      'CN-XJ-URC',
      'CN-XJ-KAR',
      'CN-XJ-TUD',
      'CN-XJ-HMD',
      'CN-XJ-CJZ',
      'CN-XJ-BOR',
      'CN-XJ-BAG',
      'CN-XJ-AKD',
      'CN-XJ-KIZ',
      'CN-XJ-KSI',
      'CN-XJ-HOD',
      'CN-XJ-ILD',
      'CN-XJ-TCD',
      'CN-XJ-ALD',
      'TW',
      'HK',
      'MO',
    ],
  },
);
